/**
 * Root Build Script
 *
 * Builds both @opkg/core (tsc) and opkg CLI (esbuild) packages.
 * This script replaces the old monolithic build that compiled from src/.
 *
 * The root package.json is the single source of truth for the version.
 * This script syncs it to sub-packages and the generated version.ts
 * before compiling.
 */

import { execSync } from 'child_process';
import { readFileSync, writeFileSync, mkdirSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, '..');

// Read version from root package.json (single source of truth)
const rootPkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
const version = rootPkg.version;

// Sync version to sub-package package.json files
for (const pkg of ['packages/core', 'packages/cli']) {
  const pkgPath = join(root, pkg, 'package.json');
  const pkgJson = JSON.parse(readFileSync(pkgPath, 'utf8'));
  if (pkgJson.version !== version) {
    pkgJson.version = version;
    writeFileSync(pkgPath, JSON.stringify(pkgJson, null, 2) + '\n');
    console.log(`Synced version ${version} → ${pkg}/package.json`);
  }
}

// Generate version.ts for @opkg/core
const generatedDir = join(root, 'packages/core/src/generated');
mkdirSync(generatedDir, { recursive: true });
writeFileSync(
  join(generatedDir, 'version.ts'),
  `// Auto-generated by build script. Do not edit manually.\nexport const VERSION = '${version}';\n`
);

console.log('Building @opkg/core...');
execSync('npm run build', { cwd: join(root, 'packages/core'), stdio: 'inherit' });

console.log('Building opkg CLI...');
execSync('npm run build', { cwd: join(root, 'packages/cli'), stdio: 'inherit' });

console.log('Build complete.');
